In [1]:
# import sys
# sys.path.append('..')

# %reload_ext autoreload
# %autoreload 2
# # %aimport sponge_networks
# # %aimport sponge_networks.utils

In [1]:
import sponge_networks as sn

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 7)
plt.rcParams["axes.grid"] = True
plt.rcParams["font.size"] = 12
%matplotlib inline

import numpy as np
import networkx as nx
import pandas as pd

## Layouts

In [2]:
nw = sn.build_sponge_network(
    grid_type="triangular", n_cols=4, n_rows=2,
    layout={
        "weights_sink_edge": 1,
        "weights_loop": 1,
        "weights_horizontal": 2,
        "weights_up_down": 5,
        "weights_down_up": 1,
    },
    generate_sinks=True,
    visual_sink_edge_length=0.6
)

In [3]:
sim = nw.run_sponge_simulation([50, 20, 20], n_iters=50)
nw.plot_simulation(sim, scale=1.4)

interactive(children=(IntSlider(value=0, description='№ of iteration', max=49), Output()), _dom_classes=('widg…

In [8]:
nw.resource_network.G.nodes()

NodeView(((0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1), (0, 2), (1, 2), (2, 2), (0, -1), (1, -1), (2, -1)))

In [14]:
R = np.array([
        [0, 1, 2],
        [1, 0, 0],
        [1, 3, 0]
    ])
rn = sn.resource_networks.ResourceNetwork(nx.from_numpy_array(R, create_using=nx.DiGraph))

In [13]:
R

array([[0, 1, 2],
       [1, 0, 0],
       [1, 3, 0]])

In [22]:
rn.stochastic_matrix

array([[0.        , 0.33333333, 0.66666667],
       [1.        , 0.        , 0.        ],
       [0.25      , 0.75      , 0.        ]])

In [33]:
v = np.array([[1, 1, 2]])
np.tensordot(v, np.array([1, 1, 1]), 0)

array([[[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2]]])

In [12]:
(np.array([1, 1, 1])@R)

array([2, 4, 2])